language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run test:ci

before_deploy:
  - npm install netlify-cli -g
  - npm run build:prod

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master